#!/bin/bash

if [ ! -f ./sbt-launch.jar ]; then
    echo "Downloading sbt-launch.jar"
    wget http://central.maven.org/maven2/org/scala-sbt/sbt-launch/1.0.2/sbt-launch-1.0.2.jar -O sbt-launch.jar
fi

java -Xss256m -jar ./sbt-launch.jar "$@"
